name: pages-auto-build-deploy
on:
  # workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.personal_token }}
          EXTERNAL_REPOSITORY: shawn0/shawn0.github.io
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: gh-pages  # 指定部署分支为gh-pages